<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>12.0</LangVersion>
    <Nullable>annotations</Nullable>
    <OutputType>Library</OutputType>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="pythonnet" Version="3.0.3" />
    <PackageReference Include="Google.OrTools" Version="9.10.4067" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="accoremgd">
        <HintPath>lib\accoremgd.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="acdbmgd">
        <HintPath>lib\acdbmgd.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="acmgd">
        <HintPath>lib\acmgd.dll</HintPath>
        <Private>False</Private>
      </Reference>

  </ItemGroup>

</Project>
